version: '1.0'
services:
  
  web:
    build:
      context: ./
      dockerfile: Dockerfile 
    volumes:
      - .:/home/TwelveWeb
      - /home/TwelveWeb/node_modules
    restart: always
    container_name: twelve_web
    ports:
      - 3000:3000